# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{smart_tuple}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Fortuna"]
  s.date = %q{2010-11-15}
  s.description = %q{A Simple Yet Smart SQL Conditions Builder}
  s.email = %q{alex.r@askit.org}
  s.extra_rdoc_files = [
    "README.html",
     "README.md"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.html",
     "README.md",
     "Rakefile",
     "VERSION.yml",
     "init.rb",
     "lib/smart_tuple.rb",
     "smart_tuple.gemspec"
  ]
  s.homepage = %q{http://github.com/dadooda/smart_tuple}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Simple Yet Smart SQL Conditions Builder}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/smart_tuple_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
